export enum ActionType {
  HYDRATE = '__NEXT_REDUX_WRAPPER_HYDRATE__',
  INCREASE_COUNT_HOME = 'INCREASE_COUNT_HOME',
  DECREASE_COUNT_HOME = 'DECREASE_COUNT_HOME',
  UPDATE_DATA_HOME = 'UPDATE_DATA_HOME',
}
