export enum AppActionType {
  HYDRATE = '__NEXT_REDUX_WRAPPER_HYDRATE__',
  UPDATE_LOCALE_APP = 'UPDATE_LOCALE_APP',
  UPDATE_SIDEBAR_COLLAPSED_APP = 'UPDATE_SIDEBAR_COLLAPSED_APP',
  UPDATE_THEME_APP = 'UPDATE_THEME_APP',
}
